### ISSUE TITLE
File format for 2017

### ISSUE THREAD

**Issue by BallHogg** [jmichaliga/btsh-ref#1]
Need the 2017 stats file in the format as a template for 2018 stats

**Comment by jmichaliga** [comment]
I just sent this to the boxscores@btsh.org email, and shared on the Google Doc to keep it somewhat private.

**Comment by jmichaliga** [comment]
https://docs.google.com/spreadsheets/d/128CMCWDUn-XIgck0HSNEdMg_-mMDe
