### ISSUE TITLE
BTSH Rosters 2021

### ISSUE THREAD

**Issue by BallHogg** [jmichaliga/btsh-ref#2]
Ball Hogg to get rosters from HicksHerr

**Comment by jmichaliga** [comment]
I don't think we ever did this. 
Let's try again this year! Updating to 2019

**Comment by notacoat** [comment]
https://docs.google.com/spreadsheets/d/1NV3cmY69BeOmL7hiYM1cwE25zTvSNMu10EYg1czMQro/edit?usp=sharing @jmichaliga
